window.CATEGORIES = [
  { id: 'brake',    name: 'سیستم ترمز',       icon: 'brake',    count: 2 },
  { id: 'susp',     name: 'سیستم تعلیق',      icon: 'susp',     count: 2 },
  { id: 'engine',   name: 'قطعات موتوری',     icon: 'engine',   count: 1 },
  { id: 'cooling',  name: 'سیستم خنک‌کننده',  icon: 'cooling',  count: 3 },
  { id: 'electric', name: 'سیستم برق',        icon: 'electric', count: 2 },
  { id: 'filter',   name: 'فیلترها',           icon: 'filter',   count: 1 },
  { id: 'trans',    name: 'انتقال قدرت',       icon: 'trans',    count: 1 },
  { id: 'body',     name: 'بدنه و تزئینات',   icon: 'body',     count: 0 },
];

window.PRODUCTS = [
  {
    id: 1,
    name: 'ترموستات سمند',
    nameEn: 'Samand Thermostat',
    image: 'pics/ترموستات سمند.jpg',
    category: 'cooling',
    categoryName: 'سیستم خنک‌کننده',
    price: 185000,
    originalPrice: 220000,
    code: 'TH-SND-001',
    brand: 'ایران یدک',
    compatible: ['سمند', 'سمند EF7', 'سمند LX', 'سمند سورن'],
    warranty: '۶ ماه',
    delivery: '۲ تا ۳ روز کاری',
    stock: true,
    badge: 'پرفروش',
    rating: 4.5,
    reviews: 23,
    description: 'ترموستات اصلی سمند مناسب برای تنظیم دمای بهینه موتور. این قطعه با جلوگیری از گرمای بیش از حد، عمر موتور را افزایش می‌دهد. دارای تأیید کیفیت ایران یدک و ساخته شده با آلیاژ استاندارد ضد زنگ.',
    specs: [
      { label: 'دمای باز شدن', value: '۸۷ درجه سانتیگراد' },
      { label: 'جنس', value: 'آلیاژ فلزی استاندارد' },
      { label: 'ابعاد', value: 'استاندارد اصلی' },
    ],
  },
  {
    id: 2,
    name: 'دیسک ترمز جلو دنا',
    nameEn: 'Dena Front Brake Disc',
    image: 'pics/دیسک ترمز جلو دنا.jpg',
    category: 'brake',
    categoryName: 'سیستم ترمز',
    price: 1250000,
    originalPrice: 1450000,
    code: 'DB-DNA-001',
    brand: 'پاکشو',
    compatible: ['دنا', 'دنا پلاس', 'دنا پلاس اتوماتیک'],
    warranty: '۱۲ ماه',
    delivery: '۱ تا ۲ روز کاری',
    stock: true,
    badge: 'تخفیف',
    rating: 4.8,
    reviews: 41,
    description: 'دیسک ترمز جلو اصلی دنا با آلیاژ گرافیتی مقاوم در برابر حرارت. طراحی شده برای عملکرد ترمزگیری بهینه در شرایط شهری و جاده‌ای. گواهی استاندارد ملی ایران و ضمانت ۱۲ ماهه.',
    specs: [
      { label: 'قطر', value: '۲۵۶ میلیمتر' },
      { label: 'ضخامت', value: '۲۲ میلیمتر' },
      { label: 'جنس', value: 'چدن گرافیتی' },
    ],
  },
  {
    id: 3,
    name: 'دیسک و صفحه کلاچ پژو ۲۰۶',
    nameEn: 'Peugeot 206 Clutch Kit',
    image: 'pics/دیسک و صفحه کلاچ پژو ۲۰۶.jpg',
    category: 'trans',
    categoryName: 'انتقال قدرت',
    price: 4850000,
    originalPrice: 5200000,
    code: 'CL-206-001',
    brand: 'LUK',
    compatible: ['پژو ۲۰۶ تیپ ۲', 'پژو ۲۰۶ تیپ ۳', 'پژو ۲۰۶ تیپ ۵', 'پژو ۲۰۶ SD'],
    warranty: '۱۸ ماه',
    delivery: '۲ تا ۴ روز کاری',
    stock: true,
    badge: 'اصل',
    rating: 4.9,
    reviews: 67,
    description: 'کیت کلاچ اصلی LUK برای پژو ۲۰۶ شامل دیسک کلاچ، صفحه کلاچ و بلبرینگ آزادساز. ساخت آلمان با رویه اصطکاکی با کیفیت بالا. مناسب برای رانندگی شهری و برون‌شهری.',
    specs: [
      { label: 'قطر دیسک', value: '۲۰۰ میلیمتر' },
      { label: 'تعداد لاملا', value: '۲۲ عدد' },
      { label: 'کشور سازنده', value: 'آلمان' },
    ],
  },
  {
    id: 4,
    name: 'دینام پراید',
    nameEn: 'Pride Alternator',
    image: 'pics/دینام پراید.jpg',
    category: 'electric',
    categoryName: 'سیستم برق',
    price: 2100000,
    originalPrice: 2350000,
    code: 'AL-PRI-001',
    brand: 'واریان',
    compatible: ['پراید ۱۳۱', 'پراید ۱۳۲', 'پراید ۱۴۱', 'پراید صبا'],
    warranty: '۱۲ ماه',
    delivery: '۱ تا ۳ روز کاری',
    stock: true,
    badge: '',
    rating: 4.3,
    reviews: 18,
    description: 'دینام بازسازی شده با کیفیت نو برای پراید. آمپراژ ۴۵ آمپر، مناسب برای تأمین برق سیستم‌های الکتریکی خودرو. تست شده ۱۰۰٪ قبل از ارسال.',
    specs: [
      { label: 'آمپراژ', value: '۴۵ آمپر' },
      { label: 'ولتاژ', value: '۱۴ ولت' },
      { label: 'نوع', value: 'بازسازی با گارانتی' },
    ],
  },
  {
    id: 5,
    name: 'رادیاتور آب تیبا',
    nameEn: 'Tiba Water Radiator',
    image: 'pics/رادیاتور آب تیبا.jpg',
    category: 'cooling',
    categoryName: 'سیستم خنک‌کننده',
    price: 3200000,
    originalPrice: 3600000,
    code: 'RD-TIB-001',
    brand: 'کیان رادیاتور',
    compatible: ['تیبا', 'تیبا ۲', 'تیبا ELX'],
    warranty: '۱۲ ماه',
    delivery: '۲ تا ۳ روز کاری',
    stock: true,
    badge: 'پرفروش',
    rating: 4.6,
    reviews: 34,
    description: 'رادیاتور آب کامل تیبا با تانک‌های پلاستیکی مقاوم و هسته آلومینیومی. طراحی بهینه برای خنک‌کاری موتور در شرایط ترافیک سنگین. ساخت داخل با کیفیت اصلی.',
    specs: [
      { label: 'جنس هسته', value: 'آلومینیوم' },
      { label: 'جنس تانک', value: 'پلاستیک مقاوم' },
      { label: 'تعداد ردیف', value: '۲ ردیف' },
    ],
  },
  {
    id: 6,
    name: 'سرسیلندر کامل پژو ۴۰۵',
    nameEn: 'Peugeot 405 Full Cylinder Head',
    image: 'pics/سرسیلندر کامل پژو ۴۰۵.jpg',
    category: 'engine',
    categoryName: 'قطعات موتوری',
    price: 8900000,
    originalPrice: 9500000,
    code: 'CH-405-001',
    brand: 'ایران خودرو یدک',
    compatible: ['پژو ۴۰۵ GLX', 'پژو ۴۰۵ SLX', 'پژو پارس', 'پژو پارس LX'],
    warranty: '۶ ماه',
    delivery: '۳ تا ۵ روز کاری',
    stock: false,
    badge: 'ناموجود',
    rating: 4.7,
    reviews: 12,
    description: 'سرسیلندر کامل پژو ۴۰۵ با واشر نو و پیچ‌های استاندارد. شامل تمام سوپاپ‌ها، فنرها و راهنماها. ریخته‌گری اصلی با استاندارد کارخانه‌ای ایران خودرو.',
    specs: [
      { label: 'تعداد سوپاپ', value: '۸ عدد' },
      { label: 'جنس', value: 'آلیاژ آلومینیوم' },
      { label: 'وضعیت', value: 'نو، کامل با واشر' },
    ],
  },
  {
    id: 7,
    name: 'طبق چرخ جلو پژو ۲۰۶',
    nameEn: 'Peugeot 206 Front Control Arm',
    image: 'pics/طبق چرخ جلو پژو ۲۰۶.jpg',
    category: 'susp',
    categoryName: 'سیستم تعلیق',
    price: 980000,
    originalPrice: 1100000,
    code: 'CM-206-001',
    brand: 'مهرام',
    compatible: ['پژو ۲۰۶ تیپ ۲', 'پژو ۲۰۶ تیپ ۳', 'پژو ۲۰۶ تیپ ۵', 'پژو ۲۰۶ SD'],
    warranty: '۶ ماه',
    delivery: '۱ تا ۲ روز کاری',
    stock: true,
    badge: '',
    rating: 4.2,
    reviews: 29,
    description: 'طبق چرخ جلو پژو ۲۰۶ با بوش‌های لاستیکی مقاوم. جلوگیری از لرزش و بهبود پایداری در هنگام رانندگی. مناسب برای سطوح جاده‌ای ایران.',
    specs: [
      { label: 'جنس', value: 'فولاد استاندارد' },
      { label: 'نوع بوش', value: 'لاستیکی' },
      { label: 'موقعیت', value: 'جلو - طرفین' },
    ],
  },
  {
    id: 8,
    name: 'فیلتر روغن (تمام مدل)',
    nameEn: 'Oil Filter (Universal)',
    image: 'pics/فیلتر روغن (تمام مدل).jpg',
    category: 'filter',
    categoryName: 'فیلترها',
    price: 145000,
    originalPrice: 170000,
    code: 'OF-ALL-001',
    brand: 'سرکان',
    compatible: ['تمام مدل‌های ایرانی', 'پراید', 'پژو', 'سمند', 'تیبا', 'دنا'],
    warranty: '۳ ماه',
    delivery: '۱ روز کاری',
    stock: true,
    badge: 'پرفروش',
    rating: 4.4,
    reviews: 89,
    description: 'فیلتر روغن یونیورسال سرکان مناسب برای اکثر خودروهای ایرانی. دارای فیلتر جانبی پشتیبان‌گیری و سوپاپ یک‌طرفه. تعویض در هر ۵۰۰۰ کیلومتر توصیه می‌شود.',
    specs: [
      { label: 'رزوه', value: 'M20×1.5' },
      { label: 'ارتفاع', value: '۷۸ میلیمتر' },
      { label: 'بازه تعویض', value: 'هر ۵۰۰۰ کیلومتر' },
    ],
  },
  {
    id: 9,
    name: 'لنت ترمز جلو پراید',
    nameEn: 'Pride Front Brake Pads',
    image: 'pics/لنت ترمز جلو پراید.jpg',
    category: 'brake',
    categoryName: 'سیستم ترمز',
    price: 390000,
    originalPrice: 450000,
    code: 'BP-PRI-001',
    brand: 'آرمان',
    compatible: ['پراید ۱۳۱', 'پراید ۱۳۲', 'پراید ۱۴۱'],
    warranty: '۶ ماه',
    delivery: '۱ روز کاری',
    stock: true,
    badge: '',
    rating: 4.1,
    reviews: 55,
    description: 'لنت ترمز جلو پراید با ترکیب اصطکاکی کم‌گرد و کم‌صدا. عملکرد ترمزگیری قابل اطمینان در جاده‌های خشک و مرطوب. فاقد آزبست و سازگار با محیط زیست.',
    specs: [
      { label: 'ترکیب', value: 'کم‌فلز' },
      { label: 'ضخامت', value: '۱۴ میلیمتر' },
      { label: 'ویژگی', value: 'کم‌صدا، کم‌گرد' },
    ],
  },
  {
    id: 10,
    name: 'واترپمپ سمند EF7',
    nameEn: 'Samand EF7 Water Pump',
    image: 'pics/واترپمپ سمند EF7.jpg',
    category: 'cooling',
    categoryName: 'سیستم خنک‌کننده',
    price: 575000,
    originalPrice: 650000,
    code: 'WP-EF7-001',
    brand: 'آبادیس',
    compatible: ['سمند EF7', 'سمند EF7i', 'سمند سورن EF7'],
    warranty: '۱۲ ماه',
    delivery: '۱ تا ۲ روز کاری',
    stock: true,
    badge: '',
    rating: 4.6,
    reviews: 31,
    description: 'واترپمپ سمند EF7 با پره‌های آلومینیومی ریخته‌گری شده. کاهش صدا و لرزش نسبت به نمونه قبلی. پوشش آنتی‌کروژن برای طول عمر بیشتر در شرایط آب و هوایی متنوع.',
    specs: [
      { label: 'جنس پره', value: 'آلومینیوم ریخته‌گری' },
      { label: 'نوع آب‌بند', value: 'ضدنشت سرامیکی' },
      { label: 'دور موتور', value: 'تا ۶۰۰۰ RPM' },
    ],
  },
  {
    id: 11,
    name: 'کمک‌فنر جلو پژو پارس',
    nameEn: 'Peugeot Pars Front Shock Absorber',
    image: 'pics/کمک‌فنر جلو پژو پارس.jpg',
    category: 'susp',
    categoryName: 'سیستم تعلیق',
    price: 1750000,
    originalPrice: 1950000,
    code: 'SA-PRS-001',
    brand: 'یاکا',
    compatible: ['پژو پارس', 'پژو پارس LX', 'پژو ۴۰۵ GLX', 'پژو ۴۰۵ SLX'],
    warranty: '۱۲ ماه',
    delivery: '۲ تا ۳ روز کاری',
    stock: true,
    badge: 'اصل',
    rating: 4.5,
    reviews: 44,
    description: 'کمک‌فنر جلو پژو پارس از برند KONI ساخت هلند با تکنولوژی ژل هیدرولیک. کاهش ۳۰٪ ارتعاش نسبت به نمونه استاندارد. مناسب برای جاده‌های ناهموار ایران.',
    specs: [
      { label: 'نوع', value: 'گازی-هیدرولیک' },
      { label: 'کشور سازنده', value: 'هلند' },
      { label: 'طول آزاد', value: '۳۹۸ میلیمتر' },
    ],
  },
  {
    id: 12,
    name: 'کوئل دوبل سمند EF7',
    nameEn: 'Samand EF7 Ignition Coil',
    image: 'pics/کوئل دوبل سمند EF7.png',
    category: 'electric',
    categoryName: 'سیستم برق',
    price: 2150000,
    originalPrice: 2400000,
    code: 'IC-EF7-001',
    brand: 'دنده‌سازان',
    compatible: ['سمند EF7', 'سمند EF7i', 'سمند سورن EF7', 'سمند LX EF7'],
    warranty: '۶ ماه',
    delivery: '۱ تا ۲ روز کاری',
    stock: true,
    badge: '',
    rating: 4.4,
    reviews: 27,
    description: 'کوئل دوبل سمند EF7 با پوشش اپوکسی ضد رطوبت. جرقه قوی‌تر نسبت به کوئل معمولی، کاهش مصرف سوخت و بهبود عملکرد موتور. سازگار با سیستم‌های انژکتوری EF7.',
    specs: [
      { label: 'نوع', value: 'کوئل دوبل DIS' },
      { label: 'ولتاژ خروجی', value: 'تا ۳۵ کیلوولت' },
      { label: 'پوشش', value: 'اپوکسی ضد رطوبت' },
    ],
  },
];
